### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by jvanbruegge** [isabelle-prover/isabelle-linter#36]
Currently there is no license file in the repository, which would mean that it is not allowed to just download this repository as the default is a strict copyright.
Could you add an appropriate license?

**Comment by Dacit** [comment]
Good point. My understanding is that we would be free to choose any license since we do not redistribute any Isabelle source code.

I propose to use the MIT license. @TheMC47 @lukasstevens, is that okay with you?

**Comment by TheMC47** [comment]
Sure thing

**Comment by jvanbruegge** [comment]
Once Lukas has given his ok, please also tag a new release that includes the new license :)

**Comment by lukasstevens** [comment]
OK

**Comment by Dacit** [comment]
Added license in bc699b5. @jvanbruegge you can directly clone the repository. A new version will be released once all other open ends are closed.
