### ISSUE TITLE
Small lint improvements

### ISSUE THREAD

**Issue by Dacit** [isabelle-prover/isabelle-linter#6]
- [x] low level apply is missing `frule`, `erule`, `drule`, `subst`, `rewrite`, `unfold`
- [ ] `intro`, `elim`, `dest` with `!?` for Global_Attribute_On_Unnamed Lemma
- [x] Lemma_Transforming_Attribute: `unfolded`
- [x] Complex_Isar_Initial_Method: should include all methods involving the simplifier: `auto`, `simp`, `clarsimp`, `bestsimp`, `slowsimp`
- [x] Typo in Force_Failure: 'forciing'

**Comment by Dacit** [comment]
Global_Attribute_On_Unnamed still open?

**Comment by TheMC47** [comment]
Yes, the parser isn't correctly handling `!` and `?`, I'd need to debug it more
